[tool.nitpick]
style = "https://raw.githubusercontent.com/wemake-services/wemake-python-styleguide/master/styles/nitpick-style-wemake.toml"


[tool.poetry]
name = "python-split-settings"
version = "1.1.0"
description = "Organize Python settings into multiple files and directories. Easily override and modify settings. Use wildcards and optional settings files."
authors = [
  "sobolevn <mail@sobolevn.me>",
  "Visa Kopu",
  "Antti Kaihola",
]
license = "BSD-2-Clause"
packages = [
  { include = "split_settings" }
]

readme = "README.md"

repository = "https://github.com/sobolevn/django-split-settings"
homepage = "https://django-split-settings.readthedocs.io"

keywords = [
  "settings",
  "configuration",
  "config",
]

classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Environment :: Web Environment",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: BSD License",
  "Operating System :: OS Independent",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Internet :: WWW/HTTP",
  "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
]


[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
mypy = "^0.910"
wemake-python-styleguide = "^0.15"
flake8-pytest-style = "^1.5"
nitpick = "^0.27"

safety = "^1.10"

pytest = "^6.2"
pytest-cov = "^2.12"
pytest-randomly = "^3.8"

sphinx = "<4.2"
sphinx-autodoc-typehints = "^1.12"
doc8 = "^0.9"
tomlkit = "^0.7"
m2r2 = "^0.3"


[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
